# -*- coding: utf-8 -*-
"""NYTIMES_BS_FINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Ey6mBiAaMPjPM1XmyqBnlKlc2qCDTB8

# NY TIMES BOOKS API PRACTICE
#####This API provides a list of books that are currently on the NY Times best-seller list.
"""

import requests

bookUrl = 'https://api.nytimes.com/svc/books/v3/lists/current/paperback-nonfiction.json?api-key=INSERT_API_KEY_HERE'

jsonResponse = requests.get('https://api.nytimes.com/svc/books/v3/lists/current/paperback-nonfiction.json?api-key=INSERT_API_KEY_HERE')

jsonResponse.status_code

jsonResponse.json()